# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: 'Browser Name'
        default: 'chrome'
      xmlfilename:
        type: string
        description: 'Enter suite xml file name'

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build mvn using testng xml
      run: mvn clean test
       -Dsurefire.suiteXmlFiles=${{inputs.xmlfilename}}
       -DbrowserName=${{inputs.browsername}}
       -Dmaven.test.failure.ignore=true

    - name: Report directory set writable permissions
      run: |
        chmod -R 777 ./Reports

#   Report Generation
    - name: Upload Extent Reports
      uses: actions/upload-artifact@v3
      with:
        name: sparkHTML
        path: ./Reports/*.html
        if-no-files-found: warn


